Repository SproutJavaSesac/versebyverse-frontend, pull requests merged in 2025-07, with the labels that each got.

#9 [#7]Fix(post): 목록 조회 Api 응답에서 값 받아오지 못하는 문제 해결, 조회 연속성 위해 posts로 단 건 경로 수정
  apis/posts.ts
  app/post/[id]/page.tsx
  app/posts/[id]/page.tsx
  components/posts/PostsList.tsx
Labels: bug

#11 [#8]Fix(post): Link 컴포넌트 이용해 각 게시글에 link 설정
  components/posts/PostsList.tsx
Labels: bug

#13 [#12]Docs(GitHub): pr, issue template, 자동 할당 workflow 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/auto-assign-issues.yml
Labels: Docs, Deploy

#19 [#14]Feat(post): 게시글 단 건 조회 API 연결, 아직 없는 것들은 mock으로 내려 줌. 한글 변경
  apis/posts.ts
  components/post-detail.tsx
  components/posts/PostsList.tsx
  components/user-profile-modal.tsx
  types/posts.ts
Labels: Bug, Feature

#24 [#17]Rename(project): package, 페이지 내부의 shoutify 이름을 verse-by-verse / 구절구절로 변경
  README.md
  app/layout.tsx
  app/page.tsx
  components/navigation.tsx
  package-lock.json
  package.json
Labels: Chore, Deploy

#16 [#15]Feat(member): 내 정보 조회 api에서 실제로 구현되지 않은 getMyInfo를 getMemberInfo로 수정
  lib/hooks/useMembers.ts
Labels: Feature

#29 [#25]Feat(comment): 특정 게시글 comment 전체 보기 order, level로 구현, api 작성 및 연결
  apis/comments.ts
  app/posts/[id]/page.tsx
  components/comments-section.tsx
  components/comments/comments-section.tsx
  types/comments.ts
  types/commons.ts
Labels: Feature

#34 [#30]Feat(post): 게시글 작성하기 구현 수정 및 api 연동, 감정, 컨셉 확정, 한글로 변경
  apis/posts.ts
  app/posts/write/page.tsx
  components/post-creation-form.tsx
  constants/index.ts
  constants/posts.ts
  lib/utils/posts.ts
  types/posts.ts
Labels: Feature

#37 [#32]Feat(error, loading): 공통으로 사용할 loading, error-boundary, error-page 컴포넌트 구현
  app/error.tsx
  app/global-error.tsx
  app/loading.tsx
  app/not-found.tsx
  app/posts/[id]/error.tsx
  app/posts/error.tsx
  app/posts/write/error.tsx
  components/protected-route.tsx
  components/ui/error-boundary.tsx
  components/ui/error-page.tsx
  components/ui/loading.tsx
Labels: Feature
